resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config
apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization
images:
- name: controller
  newName: wind-river/cloud-platform-deployment-manager
  newTag: latest
