/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1

import (
	"errors"
	"fmt"
	"strings"

	"k8s.io/apimachinery/pkg/runtime"
	ctrl "sigs.k8s.io/controller-runtime"
	logf "sigs.k8s.io/controller-runtime/pkg/log"
	"sigs.k8s.io/controller-runtime/pkg/webhook"
)

// Webhook response reasons
const PtpInterfaceAllowedReason string = "allowed to be admitted"

// log is for logging in this package.
var ptpinterfacelog = logf.Log.WithName("ptpinterface-resource")

func (r *PtpInterface) SetupWebhookWithManager(mgr ctrl.Manager) error {
	return ctrl.NewWebhookManagedBy(mgr).
		For(r).
		Complete()
}

// +kubebuilder:webhook:path=/mutate-starlingx-windriver-com-v1-ptpinterface,mutating=true,failurePolicy=fail,sideEffects=None,groups=starlingx.windriver.com,resources=ptpinterfaces,verbs=create;update,versions=v1,name=mptpinterface.kb.io,admissionReviewVersions=v1

var _ webhook.Defaulter = &PtpInterface{}

// Default implements webhook.Defaulter so a webhook will be registered for the type
func (r *PtpInterface) Default() {
	ptpinterfacelog.Info("default", "name", r.Name)

	// TODO(user): fill in your defaulting logic.
}

// Validates an incoming resource update/create request.  The intent of this validation is to perform only the
// minimum amount of validation which should normally be done by the CRD validation schema, but until kubebuilder
// supports the necessary validation annotations we need to do this in a webhook.  All other validation is left
// to the system API and any errors generated by that API will be reported in the resource status and events.
func (r *PtpInterface) validatePtpInterface() error {
	present := make(map[string]bool)
	delim := "="
	for _, parameter := range r.Spec.InterfaceParameters {

		if strings.Count(parameter, delim) != 1 || parameter[0:1] == delim {
			msg := fmt.Sprintf("Invalid parameter %s. Parameters must come in the form <parameterKey>=<parameterValue>.",
				parameter)
			return errors.New(msg)
		}

		key := strings.TrimSpace(strings.Split(parameter, delim)[0])

		if _, ok := present[key]; ok {
			msg := fmt.Sprintf("duplicate parameter keys are not allowed for %s.",
				parameter)
			return errors.New(msg)
		}
		present[key] = true

	}

	ptpinterfacelog.Info(PtpInterfaceAllowedReason)
	return nil
}

// TODO(user): change verbs to "verbs=create;update;delete" if you want to enable deletion validation.
// +kubebuilder:webhook:verbs=create;update,path=/validate-starlingx-windriver-com-v1-ptpinterface,mutating=false,failurePolicy=fail,sideEffects=None,groups=starlingx.windriver.com,resources=ptpinterfaces,versions=v1,name=vptpinterface.kb.io,admissionReviewVersions=v1

var _ webhook.Validator = &PtpInterface{}

// ValidateCreate implements webhook.Validator so a webhook will be registered for the type
func (r *PtpInterface) ValidateCreate() error {
	ptpinterfacelog.Info("validate create", "name", r.Name)

	// TODO(user): fill in your validation logic upon object creation.
	return r.validatePtpInterface()
}

// ValidateUpdate implements webhook.Validator so a webhook will be registered for the type
func (r *PtpInterface) ValidateUpdate(old runtime.Object) error {
	ptpinterfacelog.Info("validate update", "name", r.Name)

	// TODO(user): fill in your validation logic upon object update.
	return r.validatePtpInterface()
}

// ValidateDelete implements webhook.Validator so a webhook will be registered for the type
func (r *PtpInterface) ValidateDelete() error {
	ptpinterfacelog.Info("validate delete", "name", r.Name)

	// TODO(user): fill in your validation logic upon object deletion.
	return nil
}
