/* SPDX-License-Identifier: Apache-2.0 */
/* Copyright(c) 2019-2025 Wind River Systems, Inc. */
package v1

import (
	"context"
	"time"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"
)

var _ = Describe("System controller", func() {

	const (
		timeout  = time.Second * 30
		interval = time.Millisecond * 500
	)

	Context("With data", func() {
		It("Should created successfully", func() {
			ctx := context.Background()
			key := types.NamespacedName{
				Name:      "foo",
				Namespace: "default",
			}
			description := string("A sample description")
			location := string("A sample location")
			contact := string("A sample contact")
			latitude := string("45.35189954974955")
			longitude := string("-75.91866628453701")
			dnsServers := DNSServerList{"8.8.8.8", "4.4.4.4"}
			ntpServers := []string{"time.ntp.org", "1.2.3.4"}
			ptpMode := "hardware"
			created := &System{
				ObjectMeta: metav1.ObjectMeta{
					Name:      "foo",
					Namespace: "default",
				},
				Spec: SystemSpec{
					Description: &description,
					Location:    &location,
					Latitude:    &latitude,
					Longitude:   &longitude,
					Contact:     &contact,
					DNSServers:  dnsServers,
					NTPServers:  ntpServers,
					PTP: &PTPInfo{
						Mode: &ptpMode,
					},
				},
			}
			Expect(k8sClient.Create(ctx, created)).To(Succeed())

			fetched := &System{}

			Eventually(func() bool {
				err := k8sClient.Get(ctx, key, fetched)
				return err == nil
			}, timeout, interval).Should(BeTrue())
			Expect(fetched).To(Equal(created))

			updated := fetched.DeepCopy()
			updated.Labels = map[string]string{"hello": "world"}
			Expect(k8sClient.Update(ctx, updated)).To(Succeed())

			Eventually(func() bool {
				err := k8sClient.Get(ctx, key, fetched)
				return err == nil
			}, timeout, interval).Should(BeTrue())
			Expect(fetched).To(Equal(updated))

			Expect(k8sClient.Delete(ctx, fetched)).To(Succeed())
			Eventually(func() bool {
				err := k8sClient.Get(ctx, key, fetched)
				return err == nil
			}, timeout, interval).Should(BeFalse())
		})
	})

	Describe("DeepEqual function", func() {
		// The Certificates DeepEqual function is auto-generated by deepequal-gen, which
		// handles array type generation. We must manually verify SystemSpec equality
		// since deepequal-gen doesn't generate code for array attributes.
		Context("Certificates", func() {
			It("Should match unordered arrays", func() {
				other := SystemSpec{
					Certificates: CertificateList{
						{
							Type:   "ssl",
							Secret: "secret1",
						}, {
							Type:   "ssl",
							Secret: "secret3",
						}, {
							Type:   "ssl",
							Secret: "secret2",
						},
					},
				}
				in := SystemSpec{
					Certificates: CertificateList{
						{
							Type:   "ssl",
							Secret: "secret2",
						},
						{
							Type:   "ssl",
							Secret: "secret1",
						},
						{
							Type:   "ssl",
							Secret: "secret3",
						},
					}}
				Expect(in.DeepEqual(&other)).To(BeTrue())
			})

			It("Should not match if arrays are different", func() {
				in := SystemSpec{
					Certificates: CertificateList{
						{
							Type:   "ssl",
							Secret: "secret",
						},
					},
				}

				other := SystemSpec{}
				Expect(in.DeepEqual(&other)).To(BeFalse())
			})
		})

		// The ServieParameters DeepEqual function is auto-generated by deepequal-gen, which
		// handles array type generation. We must manually verify SystemSpec equality
		// since deepequal-gen doesn't generate code for array attributes.
		Context("ServiceParameters", func() {
			It("Should match unordered arrays", func() {
				in := SystemSpec{
					ServiceParameters: ServiceParameterList{
						{
							Service:    "sysinv",
							Section:    "global",
							ParamName:  "param1",
							ParamValue: "1",
						},
						{
							Service:    "sysinv",
							Section:    "global",
							ParamName:  "param2",
							ParamValue: "2",
						},
					},
				}
				other := SystemSpec{
					ServiceParameters: ServiceParameterList{
						{
							Service:    "sysinv",
							Section:    "global",
							ParamName:  "param2",
							ParamValue: "2",
						},
						{
							Service:    "sysinv",
							Section:    "global",
							ParamName:  "param1",
							ParamValue: "1",
						},
					},
				}
				Expect(in.DeepEqual(&other)).To(BeTrue())
			})

			It("Should not match if arrays are different", func() {
				in := SystemSpec{
					ServiceParameters: ServiceParameterList{
						{
							Service:    "sysinv",
							Section:    "global",
							ParamName:  "param",
							ParamValue: "value",
						},
					},
				}

				other := SystemSpec{}
				Expect(in.DeepEqual(&other)).To(BeFalse())
			})
		})

		Context("When both type and secret are same but signature is different in 2 entities", func() {
			It("Returns true", func() {
				other := &CertificateInfo{
					Type:   "ssl",
					Secret: "secret",
				}
				in := &CertificateInfo{
					Signature: "",
					Type:      "ssl",
					Secret:    "secret",
				}
				out := in.DeepEqual(other)
				Expect(out).To(BeTrue())
			})
		})

		Context("When type, secret  and signature are same in 2 entities", func() {
			It("Returns true", func() {
				other := &CertificateInfo{
					Type:      "ssl",
					Secret:    "secret",
					Signature: "signature",
				}
				in := &CertificateInfo{
					Signature: "signature",
					Type:      "ssl",
					Secret:    "secret",
				}
				out := in.DeepEqual(other)
				Expect(out).To(BeTrue())
			})
		})
	})

	Describe("Test IsKeyEqual function", func() {
		Context("When both type and secret are same but signature is different in 2 entities", func() {
			It("Returns true", func() {
				x := CertificateInfo{
					Type:   "ssl",
					Secret: "secret",
				}
				in := CertificateInfo{
					Signature: "",
					Type:      "ssl",
					Secret:    "secret",
				}
				out := in.IsKeyEqual(x)
				Expect(out).To(BeTrue())
			})
		})

		Context("When type, secret  and signature are same in 2 entities", func() {
			It("Returns true", func() {
				x := CertificateInfo{
					Signature: "signature",
					Type:      "ssl",
					Secret:    "secret",
				}
				in := CertificateInfo{
					Signature: "signature",
					Type:      "ssl",
					Secret:    "secret",
				}
				out := in.IsKeyEqual(x)
				Expect(out).To(BeTrue())
			})
		})
	})
})
