//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/* SPDX-License-Identifier: Apache-2.0 */
/* Copyright(c) 2019-2022 Wind River Systems, Inc. */

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AddressInfo) DeepCopyInto(out *AddressInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AddressInfo.
func (in *AddressInfo) DeepCopy() *AddressInfo {
	if in == nil {
		return nil
	}
	out := new(AddressInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in AddressList) DeepCopyInto(out *AddressList) {
	{
		in := &in
		*out = make(AddressList, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AddressList.
func (in AddressList) DeepCopy() AddressList {
	if in == nil {
		return nil
	}
	out := new(AddressList)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllocationInfo) DeepCopyInto(out *AllocationInfo) {
	*out = *in
	if in.Ranges != nil {
		in, out := &in.Ranges, &out.Ranges
		*out = make([]AllocationRange, len(*in))
		copy(*out, *in)
	}
	if in.Order != nil {
		in, out := &in.Order, &out.Order
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllocationInfo.
func (in *AllocationInfo) DeepCopy() *AllocationInfo {
	if in == nil {
		return nil
	}
	out := new(AllocationInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllocationRange) DeepCopyInto(out *AllocationRange) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllocationRange.
func (in *AllocationRange) DeepCopy() *AllocationRange {
	if in == nil {
		return nil
	}
	out := new(AllocationRange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BMCredentials) DeepCopyInto(out *BMCredentials) {
	*out = *in
	if in.Password != nil {
		in, out := &in.Password, &out.Password
		*out = new(BMPasswordInfo)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BMCredentials.
func (in *BMCredentials) DeepCopy() *BMCredentials {
	if in == nil {
		return nil
	}
	out := new(BMCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BMInfo) DeepCopyInto(out *BMInfo) {
	*out = *in
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.Address != nil {
		in, out := &in.Address, &out.Address
		*out = new(string)
		**out = **in
	}
	if in.Credentials != nil {
		in, out := &in.Credentials, &out.Credentials
		*out = new(BMCredentials)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BMInfo.
func (in *BMInfo) DeepCopy() *BMInfo {
	if in == nil {
		return nil
	}
	out := new(BMInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BMPasswordInfo) DeepCopyInto(out *BMPasswordInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BMPasswordInfo.
func (in *BMPasswordInfo) DeepCopy() *BMPasswordInfo {
	if in == nil {
		return nil
	}
	out := new(BMPasswordInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BondInfo) DeepCopyInto(out *BondInfo) {
	*out = *in
	in.CommonInterfaceInfo.DeepCopyInto(&out.CommonInterfaceInfo)
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TransmitHashPolicy != nil {
		in, out := &in.TransmitHashPolicy, &out.TransmitHashPolicy
		*out = new(string)
		**out = **in
	}
	if in.PrimaryReselect != nil {
		in, out := &in.PrimaryReselect, &out.PrimaryReselect
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BondInfo.
func (in *BondInfo) DeepCopy() *BondInfo {
	if in == nil {
		return nil
	}
	out := new(BondInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in BondList) DeepCopyInto(out *BondList) {
	{
		in := &in
		*out = make(BondList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BondList.
func (in BondList) DeepCopy() BondList {
	if in == nil {
		return nil
	}
	out := new(BondList)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateInfo) DeepCopyInto(out *CertificateInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateInfo.
func (in *CertificateInfo) DeepCopy() *CertificateInfo {
	if in == nil {
		return nil
	}
	out := new(CertificateInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in CertificateList) DeepCopyInto(out *CertificateList) {
	{
		in := &in
		*out = make(CertificateList, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateList.
func (in CertificateList) DeepCopy() CertificateList {
	if in == nil {
		return nil
	}
	out := new(CertificateList)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonInterfaceInfo) DeepCopyInto(out *CommonInterfaceInfo) {
	*out = *in
	if in.MTU != nil {
		in, out := &in.MTU, &out.MTU
		*out = new(int)
		**out = **in
	}
	if in.PlatformNetworks != nil {
		in, out := &in.PlatformNetworks, &out.PlatformNetworks
		*out = new(PlatformNetworkItemList)
		if **in != nil {
			in, out := *in, *out
			*out = make(PlatformNetworkItemList, len(*in))
			copy(*out, *in)
		}
	}
	if in.DataNetworks != nil {
		in, out := &in.DataNetworks, &out.DataNetworks
		*out = new(DataNetworkItemList)
		if **in != nil {
			in, out := *in, *out
			*out = make(DataNetworkItemList, len(*in))
			copy(*out, *in)
		}
	}
	if in.PTPRole != nil {
		in, out := &in.PTPRole, &out.PTPRole
		*out = new(string)
		**out = **in
	}
	if in.PtpInterfaces != nil {
		in, out := &in.PtpInterfaces, &out.PtpInterfaces
		*out = new(PtpInterfaceItemList)
		if **in != nil {
			in, out := *in, *out
			*out = make(PtpInterfaceItemList, len(*in))
			copy(*out, *in)
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonInterfaceInfo.
func (in *CommonInterfaceInfo) DeepCopy() *CommonInterfaceInfo {
	if in == nil {
		return nil
	}
	out := new(CommonInterfaceInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerFileSystemInfo) DeepCopyInto(out *ControllerFileSystemInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerFileSystemInfo.
func (in *ControllerFileSystemInfo) DeepCopy() *ControllerFileSystemInfo {
	if in == nil {
		return nil
	}
	out := new(ControllerFileSystemInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in ControllerFileSystemList) DeepCopyInto(out *ControllerFileSystemList) {
	{
		in := &in
		*out = make(ControllerFileSystemList, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerFileSystemList.
func (in ControllerFileSystemList) DeepCopy() ControllerFileSystemList {
	if in == nil {
		return nil
	}
	out := new(ControllerFileSystemList)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in DNSServerList) DeepCopyInto(out *DNSServerList) {
	{
		in := &in
		*out = make(DNSServerList, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSServerList.
func (in DNSServerList) DeepCopy() DNSServerList {
	if in == nil {
		return nil
	}
	out := new(DNSServerList)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DRBDConfiguration) DeepCopyInto(out *DRBDConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DRBDConfiguration.
func (in *DRBDConfiguration) DeepCopy() *DRBDConfiguration {
	if in == nil {
		return nil
	}
	out := new(DRBDConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataNetwork) DeepCopyInto(out *DataNetwork) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataNetwork.
func (in *DataNetwork) DeepCopy() *DataNetwork {
	if in == nil {
		return nil
	}
	out := new(DataNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DataNetwork) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in DataNetworkItemList) DeepCopyInto(out *DataNetworkItemList) {
	{
		in := &in
		*out = make(DataNetworkItemList, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataNetworkItemList.
func (in DataNetworkItemList) DeepCopy() DataNetworkItemList {
	if in == nil {
		return nil
	}
	out := new(DataNetworkItemList)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataNetworkList) DeepCopyInto(out *DataNetworkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DataNetwork, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataNetworkList.
func (in *DataNetworkList) DeepCopy() *DataNetworkList {
	if in == nil {
		return nil
	}
	out := new(DataNetworkList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DataNetworkList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataNetworkSpec) DeepCopyInto(out *DataNetworkSpec) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.MTU != nil {
		in, out := &in.MTU, &out.MTU
		*out = new(int)
		**out = **in
	}
	if in.VxLAN != nil {
		in, out := &in.VxLAN, &out.VxLAN
		*out = new(VxLANInfo)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataNetworkSpec.
func (in *DataNetworkSpec) DeepCopy() *DataNetworkSpec {
	if in == nil {
		return nil
	}
	out := new(DataNetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataNetworkStatus) DeepCopyInto(out *DataNetworkStatus) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataNetworkStatus.
func (in *DataNetworkStatus) DeepCopy() *DataNetworkStatus {
	if in == nil {
		return nil
	}
	out := new(DataNetworkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ErrMissingSystemResource) DeepCopyInto(out *ErrMissingSystemResource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ErrMissingSystemResource.
func (in *ErrMissingSystemResource) DeepCopy() *ErrMissingSystemResource {
	if in == nil {
		return nil
	}
	out := new(ErrMissingSystemResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EthernetInfo) DeepCopyInto(out *EthernetInfo) {
	*out = *in
	in.CommonInterfaceInfo.DeepCopyInto(&out.CommonInterfaceInfo)
	if in.VFCount != nil {
		in, out := &in.VFCount, &out.VFCount
		*out = new(int)
		**out = **in
	}
	if in.VFDriver != nil {
		in, out := &in.VFDriver, &out.VFDriver
		*out = new(string)
		**out = **in
	}
	out.Port = in.Port
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EthernetInfo.
func (in *EthernetInfo) DeepCopy() *EthernetInfo {
	if in == nil {
		return nil
	}
	out := new(EthernetInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in EthernetList) DeepCopyInto(out *EthernetList) {
	{
		in := &in
		*out = make(EthernetList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EthernetList.
func (in EthernetList) DeepCopy() EthernetList {
	if in == nil {
		return nil
	}
	out := new(EthernetList)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EthernetPortInfo) DeepCopyInto(out *EthernetPortInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EthernetPortInfo.
func (in *EthernetPortInfo) DeepCopy() *EthernetPortInfo {
	if in == nil {
		return nil
	}
	out := new(EthernetPortInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileSystemInfo) DeepCopyInto(out *FileSystemInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileSystemInfo.
func (in *FileSystemInfo) DeepCopy() *FileSystemInfo {
	if in == nil {
		return nil
	}
	out := new(FileSystemInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in FileSystemList) DeepCopyInto(out *FileSystemList) {
	{
		in := &in
		*out = make(FileSystemList, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileSystemList.
func (in FileSystemList) DeepCopy() FileSystemList {
	if in == nil {
		return nil
	}
	out := new(FileSystemList)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Host) DeepCopyInto(out *Host) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Host.
func (in *Host) DeepCopy() *Host {
	if in == nil {
		return nil
	}
	out := new(Host)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Host) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostList) DeepCopyInto(out *HostList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Host, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostList.
func (in *HostList) DeepCopy() *HostList {
	if in == nil {
		return nil
	}
	out := new(HostList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HostList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostProfile) DeepCopyInto(out *HostProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostProfile.
func (in *HostProfile) DeepCopy() *HostProfile {
	if in == nil {
		return nil
	}
	out := new(HostProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HostProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostProfileList) DeepCopyInto(out *HostProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HostProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostProfileList.
func (in *HostProfileList) DeepCopy() *HostProfileList {
	if in == nil {
		return nil
	}
	out := new(HostProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HostProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostProfileSpec) DeepCopyInto(out *HostProfileSpec) {
	*out = *in
	if in.Base != nil {
		in, out := &in.Base, &out.Base
		*out = new(string)
		**out = **in
	}
	in.ProfileBaseAttributes.DeepCopyInto(&out.ProfileBaseAttributes)
	if in.BoardManagement != nil {
		in, out := &in.BoardManagement, &out.BoardManagement
		*out = new(BMInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.Processors != nil {
		in, out := &in.Processors, &out.Processors
		*out = make(ProcessorNodeList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		*out = make(MemoryNodeList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(ProfileStorageInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.Interfaces != nil {
		in, out := &in.Interfaces, &out.Interfaces
		*out = new(InterfaceInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make(AddressList, len(*in))
		copy(*out, *in)
	}
	if in.Routes != nil {
		in, out := &in.Routes, &out.Routes
		*out = make(RouteList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostProfileSpec.
func (in *HostProfileSpec) DeepCopy() *HostProfileSpec {
	if in == nil {
		return nil
	}
	out := new(HostProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostSpec) DeepCopyInto(out *HostSpec) {
	*out = *in
	if in.Match != nil {
		in, out := &in.Match, &out.Match
		*out = new(MatchInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.Overrides != nil {
		in, out := &in.Overrides, &out.Overrides
		*out = new(HostProfileSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostSpec.
func (in *HostSpec) DeepCopy() *HostSpec {
	if in == nil {
		return nil
	}
	out := new(HostSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostStatus) DeepCopyInto(out *HostStatus) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.AdministrativeState != nil {
		in, out := &in.AdministrativeState, &out.AdministrativeState
		*out = new(string)
		**out = **in
	}
	if in.OperationalStatus != nil {
		in, out := &in.OperationalStatus, &out.OperationalStatus
		*out = new(string)
		**out = **in
	}
	if in.AvailabilityStatus != nil {
		in, out := &in.AvailabilityStatus, &out.AvailabilityStatus
		*out = new(string)
		**out = **in
	}
	if in.Defaults != nil {
		in, out := &in.Defaults, &out.Defaults
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostStatus.
func (in *HostStatus) DeepCopy() *HostStatus {
	if in == nil {
		return nil
	}
	out := new(HostStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InterfaceInfo) DeepCopyInto(out *InterfaceInfo) {
	*out = *in
	if in.Ethernet != nil {
		in, out := &in.Ethernet, &out.Ethernet
		*out = make(EthernetList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VLAN != nil {
		in, out := &in.VLAN, &out.VLAN
		*out = make(VLANList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Bond != nil {
		in, out := &in.Bond, &out.Bond
		*out = make(BondList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VF != nil {
		in, out := &in.VF, &out.VF
		*out = make(VFList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InterfaceInfo.
func (in *InterfaceInfo) DeepCopy() *InterfaceInfo {
	if in == nil {
		return nil
	}
	out := new(InterfaceInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JournalInfo) DeepCopyInto(out *JournalInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JournalInfo.
func (in *JournalInfo) DeepCopy() *JournalInfo {
	if in == nil {
		return nil
	}
	out := new(JournalInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LicenseInfo) DeepCopyInto(out *LicenseInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LicenseInfo.
func (in *LicenseInfo) DeepCopy() *LicenseInfo {
	if in == nil {
		return nil
	}
	out := new(LicenseInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MatchBMInfo) DeepCopyInto(out *MatchBMInfo) {
	*out = *in
	if in.Address != nil {
		in, out := &in.Address, &out.Address
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatchBMInfo.
func (in *MatchBMInfo) DeepCopy() *MatchBMInfo {
	if in == nil {
		return nil
	}
	out := new(MatchBMInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MatchDMIInfo) DeepCopyInto(out *MatchDMIInfo) {
	*out = *in
	if in.SerialNumber != nil {
		in, out := &in.SerialNumber, &out.SerialNumber
		*out = new(string)
		**out = **in
	}
	if in.AssetTag != nil {
		in, out := &in.AssetTag, &out.AssetTag
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatchDMIInfo.
func (in *MatchDMIInfo) DeepCopy() *MatchDMIInfo {
	if in == nil {
		return nil
	}
	out := new(MatchDMIInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MatchInfo) DeepCopyInto(out *MatchInfo) {
	*out = *in
	if in.BootMAC != nil {
		in, out := &in.BootMAC, &out.BootMAC
		*out = new(string)
		**out = **in
	}
	if in.BoardManagement != nil {
		in, out := &in.BoardManagement, &out.BoardManagement
		*out = new(MatchBMInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.DMI != nil {
		in, out := &in.DMI, &out.DMI
		*out = new(MatchDMIInfo)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatchInfo.
func (in *MatchInfo) DeepCopy() *MatchInfo {
	if in == nil {
		return nil
	}
	out := new(MatchInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemoryFunctionInfo) DeepCopyInto(out *MemoryFunctionInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemoryFunctionInfo.
func (in *MemoryFunctionInfo) DeepCopy() *MemoryFunctionInfo {
	if in == nil {
		return nil
	}
	out := new(MemoryFunctionInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in MemoryFunctionList) DeepCopyInto(out *MemoryFunctionList) {
	{
		in := &in
		*out = make(MemoryFunctionList, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemoryFunctionList.
func (in MemoryFunctionList) DeepCopy() MemoryFunctionList {
	if in == nil {
		return nil
	}
	out := new(MemoryFunctionList)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemoryNodeInfo) DeepCopyInto(out *MemoryNodeInfo) {
	*out = *in
	if in.Functions != nil {
		in, out := &in.Functions, &out.Functions
		*out = make(MemoryFunctionList, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemoryNodeInfo.
func (in *MemoryNodeInfo) DeepCopy() *MemoryNodeInfo {
	if in == nil {
		return nil
	}
	out := new(MemoryNodeInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in MemoryNodeList) DeepCopyInto(out *MemoryNodeList) {
	{
		in := &in
		*out = make(MemoryNodeList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemoryNodeList.
func (in MemoryNodeList) DeepCopy() MemoryNodeList {
	if in == nil {
		return nil
	}
	out := new(MemoryNodeList)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitorInfo) DeepCopyInto(out *MonitorInfo) {
	*out = *in
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitorInfo.
func (in *MonitorInfo) DeepCopy() *MonitorInfo {
	if in == nil {
		return nil
	}
	out := new(MonitorInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in NTPServerList) DeepCopyInto(out *NTPServerList) {
	{
		in := &in
		*out = make(NTPServerList, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NTPServerList.
func (in NTPServerList) DeepCopy() NTPServerList {
	if in == nil {
		return nil
	}
	out := new(NTPServerList)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OSDInfo) DeepCopyInto(out *OSDInfo) {
	*out = *in
	if in.ClusterName != nil {
		in, out := &in.ClusterName, &out.ClusterName
		*out = new(string)
		**out = **in
	}
	if in.Journal != nil {
		in, out := &in.Journal, &out.Journal
		*out = new(JournalInfo)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OSDInfo.
func (in *OSDInfo) DeepCopy() *OSDInfo {
	if in == nil {
		return nil
	}
	out := new(OSDInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in OSDList) DeepCopyInto(out *OSDList) {
	{
		in := &in
		*out = make(OSDList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OSDList.
func (in OSDList) DeepCopy() OSDList {
	if in == nil {
		return nil
	}
	out := new(OSDList)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PTPInfo) DeepCopyInto(out *PTPInfo) {
	*out = *in
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(string)
		**out = **in
	}
	if in.Transport != nil {
		in, out := &in.Transport, &out.Transport
		*out = new(string)
		**out = **in
	}
	if in.Mechanism != nil {
		in, out := &in.Mechanism, &out.Mechanism
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PTPInfo.
func (in *PTPInfo) DeepCopy() *PTPInfo {
	if in == nil {
		return nil
	}
	out := new(PTPInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PhysicalVolumeInfo) DeepCopyInto(out *PhysicalVolumeInfo) {
	*out = *in
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PhysicalVolumeInfo.
func (in *PhysicalVolumeInfo) DeepCopy() *PhysicalVolumeInfo {
	if in == nil {
		return nil
	}
	out := new(PhysicalVolumeInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in PhysicalVolumeList) DeepCopyInto(out *PhysicalVolumeList) {
	{
		in := &in
		*out = make(PhysicalVolumeList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PhysicalVolumeList.
func (in PhysicalVolumeList) DeepCopy() PhysicalVolumeList {
	if in == nil {
		return nil
	}
	out := new(PhysicalVolumeList)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformNetwork) DeepCopyInto(out *PlatformNetwork) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformNetwork.
func (in *PlatformNetwork) DeepCopy() *PlatformNetwork {
	if in == nil {
		return nil
	}
	out := new(PlatformNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PlatformNetwork) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in PlatformNetworkItemList) DeepCopyInto(out *PlatformNetworkItemList) {
	{
		in := &in
		*out = make(PlatformNetworkItemList, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformNetworkItemList.
func (in PlatformNetworkItemList) DeepCopy() PlatformNetworkItemList {
	if in == nil {
		return nil
	}
	out := new(PlatformNetworkItemList)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformNetworkList) DeepCopyInto(out *PlatformNetworkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PlatformNetwork, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformNetworkList.
func (in *PlatformNetworkList) DeepCopy() *PlatformNetworkList {
	if in == nil {
		return nil
	}
	out := new(PlatformNetworkList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PlatformNetworkList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformNetworkSpec) DeepCopyInto(out *PlatformNetworkSpec) {
	*out = *in
	if in.Gateway != nil {
		in, out := &in.Gateway, &out.Gateway
		*out = new(string)
		**out = **in
	}
	in.Allocation.DeepCopyInto(&out.Allocation)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformNetworkSpec.
func (in *PlatformNetworkSpec) DeepCopy() *PlatformNetworkSpec {
	if in == nil {
		return nil
	}
	out := new(PlatformNetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformNetworkStatus) DeepCopyInto(out *PlatformNetworkStatus) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.PoolUUID != nil {
		in, out := &in.PoolUUID, &out.PoolUUID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformNetworkStatus.
func (in *PlatformNetworkStatus) DeepCopy() *PlatformNetworkStatus {
	if in == nil {
		return nil
	}
	out := new(PlatformNetworkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProcessorFunctionInfo) DeepCopyInto(out *ProcessorFunctionInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProcessorFunctionInfo.
func (in *ProcessorFunctionInfo) DeepCopy() *ProcessorFunctionInfo {
	if in == nil {
		return nil
	}
	out := new(ProcessorFunctionInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in ProcessorFunctionList) DeepCopyInto(out *ProcessorFunctionList) {
	{
		in := &in
		*out = make(ProcessorFunctionList, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProcessorFunctionList.
func (in ProcessorFunctionList) DeepCopy() ProcessorFunctionList {
	if in == nil {
		return nil
	}
	out := new(ProcessorFunctionList)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProcessorInfo) DeepCopyInto(out *ProcessorInfo) {
	*out = *in
	if in.Functions != nil {
		in, out := &in.Functions, &out.Functions
		*out = make(ProcessorFunctionList, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProcessorInfo.
func (in *ProcessorInfo) DeepCopy() *ProcessorInfo {
	if in == nil {
		return nil
	}
	out := new(ProcessorInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in ProcessorNodeList) DeepCopyInto(out *ProcessorNodeList) {
	{
		in := &in
		*out = make(ProcessorNodeList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProcessorNodeList.
func (in ProcessorNodeList) DeepCopy() ProcessorNodeList {
	if in == nil {
		return nil
	}
	out := new(ProcessorNodeList)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProfileBaseAttributes) DeepCopyInto(out *ProfileBaseAttributes) {
	*out = *in
	if in.Personality != nil {
		in, out := &in.Personality, &out.Personality
		*out = new(string)
		**out = **in
	}
	if in.AdministrativeState != nil {
		in, out := &in.AdministrativeState, &out.AdministrativeState
		*out = new(string)
		**out = **in
	}
	if in.SubFunctions != nil {
		in, out := &in.SubFunctions, &out.SubFunctions
		*out = make([]SubFunction, len(*in))
		copy(*out, *in)
	}
	if in.Location != nil {
		in, out := &in.Location, &out.Location
		*out = new(string)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.InstallOutput != nil {
		in, out := &in.InstallOutput, &out.InstallOutput
		*out = new(string)
		**out = **in
	}
	if in.Console != nil {
		in, out := &in.Console, &out.Console
		*out = new(string)
		**out = **in
	}
	if in.BootDevice != nil {
		in, out := &in.BootDevice, &out.BootDevice
		*out = new(string)
		**out = **in
	}
	if in.PowerOn != nil {
		in, out := &in.PowerOn, &out.PowerOn
		*out = new(bool)
		**out = **in
	}
	if in.ProvisioningMode != nil {
		in, out := &in.ProvisioningMode, &out.ProvisioningMode
		*out = new(string)
		**out = **in
	}
	if in.BootMAC != nil {
		in, out := &in.BootMAC, &out.BootMAC
		*out = new(string)
		**out = **in
	}
	if in.PtpInstances != nil {
		in, out := &in.PtpInstances, &out.PtpInstances
		*out = make(PtpInstanceItemList, len(*in))
		copy(*out, *in)
	}
	if in.RootDevice != nil {
		in, out := &in.RootDevice, &out.RootDevice
		*out = new(string)
		**out = **in
	}
	if in.ClockSynchronization != nil {
		in, out := &in.ClockSynchronization, &out.ClockSynchronization
		*out = new(string)
		**out = **in
	}
	if in.MaxCPUMhzConfigured != nil {
		in, out := &in.MaxCPUMhzConfigured, &out.MaxCPUMhzConfigured
		*out = new(string)
		**out = **in
	}
	if in.AppArmor != nil {
		in, out := &in.AppArmor, &out.AppArmor
		*out = new(string)
		**out = **in
	}
	if in.HwSettle != nil {
		in, out := &in.HwSettle, &out.HwSettle
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProfileBaseAttributes.
func (in *ProfileBaseAttributes) DeepCopy() *ProfileBaseAttributes {
	if in == nil {
		return nil
	}
	out := new(ProfileBaseAttributes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProfileStorageInfo) DeepCopyInto(out *ProfileStorageInfo) {
	*out = *in
	if in.Monitor != nil {
		in, out := &in.Monitor, &out.Monitor
		*out = new(MonitorInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.OSDs != nil {
		in, out := &in.OSDs, &out.OSDs
		*out = new(OSDList)
		if **in != nil {
			in, out := *in, *out
			*out = make(OSDList, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
	if in.VolumeGroups != nil {
		in, out := &in.VolumeGroups, &out.VolumeGroups
		*out = new(VolumeGroupList)
		if **in != nil {
			in, out := *in, *out
			*out = make(VolumeGroupList, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
	if in.FileSystems != nil {
		in, out := &in.FileSystems, &out.FileSystems
		*out = new(FileSystemList)
		if **in != nil {
			in, out := *in, *out
			*out = make(FileSystemList, len(*in))
			copy(*out, *in)
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProfileStorageInfo.
func (in *ProfileStorageInfo) DeepCopy() *ProfileStorageInfo {
	if in == nil {
		return nil
	}
	out := new(ProfileStorageInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PtpInstance) DeepCopyInto(out *PtpInstance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PtpInstance.
func (in *PtpInstance) DeepCopy() *PtpInstance {
	if in == nil {
		return nil
	}
	out := new(PtpInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PtpInstance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in PtpInstanceItemList) DeepCopyInto(out *PtpInstanceItemList) {
	{
		in := &in
		*out = make(PtpInstanceItemList, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PtpInstanceItemList.
func (in PtpInstanceItemList) DeepCopy() PtpInstanceItemList {
	if in == nil {
		return nil
	}
	out := new(PtpInstanceItemList)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PtpInstanceList) DeepCopyInto(out *PtpInstanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PtpInstance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PtpInstanceList.
func (in *PtpInstanceList) DeepCopy() *PtpInstanceList {
	if in == nil {
		return nil
	}
	out := new(PtpInstanceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PtpInstanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PtpInstanceSpec) DeepCopyInto(out *PtpInstanceSpec) {
	*out = *in
	if in.InstanceParameters != nil {
		in, out := &in.InstanceParameters, &out.InstanceParameters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PtpInstanceSpec.
func (in *PtpInstanceSpec) DeepCopy() *PtpInstanceSpec {
	if in == nil {
		return nil
	}
	out := new(PtpInstanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PtpInstanceStatus) DeepCopyInto(out *PtpInstanceStatus) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PtpInstanceStatus.
func (in *PtpInstanceStatus) DeepCopy() *PtpInstanceStatus {
	if in == nil {
		return nil
	}
	out := new(PtpInstanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PtpInterface) DeepCopyInto(out *PtpInterface) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PtpInterface.
func (in *PtpInterface) DeepCopy() *PtpInterface {
	if in == nil {
		return nil
	}
	out := new(PtpInterface)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PtpInterface) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in PtpInterfaceItemList) DeepCopyInto(out *PtpInterfaceItemList) {
	{
		in := &in
		*out = make(PtpInterfaceItemList, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PtpInterfaceItemList.
func (in PtpInterfaceItemList) DeepCopy() PtpInterfaceItemList {
	if in == nil {
		return nil
	}
	out := new(PtpInterfaceItemList)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PtpInterfaceList) DeepCopyInto(out *PtpInterfaceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PtpInterface, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PtpInterfaceList.
func (in *PtpInterfaceList) DeepCopy() *PtpInterfaceList {
	if in == nil {
		return nil
	}
	out := new(PtpInterfaceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PtpInterfaceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PtpInterfaceSpec) DeepCopyInto(out *PtpInterfaceSpec) {
	*out = *in
	if in.InterfaceParameters != nil {
		in, out := &in.InterfaceParameters, &out.InterfaceParameters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PtpInterfaceSpec.
func (in *PtpInterfaceSpec) DeepCopy() *PtpInterfaceSpec {
	if in == nil {
		return nil
	}
	out := new(PtpInterfaceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PtpInterfaceStatus) DeepCopyInto(out *PtpInterfaceStatus) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PtpInterfaceStatus.
func (in *PtpInterfaceStatus) DeepCopy() *PtpInterfaceStatus {
	if in == nil {
		return nil
	}
	out := new(PtpInterfaceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouteInfo) DeepCopyInto(out *RouteInfo) {
	*out = *in
	if in.Metric != nil {
		in, out := &in.Metric, &out.Metric
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouteInfo.
func (in *RouteInfo) DeepCopy() *RouteInfo {
	if in == nil {
		return nil
	}
	out := new(RouteInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in RouteList) DeepCopyInto(out *RouteList) {
	{
		in := &in
		*out = make(RouteList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouteList.
func (in RouteList) DeepCopy() RouteList {
	if in == nil {
		return nil
	}
	out := new(RouteList)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceParameterInfo) DeepCopyInto(out *ServiceParameterInfo) {
	*out = *in
	if in.Personality != nil {
		in, out := &in.Personality, &out.Personality
		*out = new(string)
		**out = **in
	}
	if in.Resource != nil {
		in, out := &in.Resource, &out.Resource
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceParameterInfo.
func (in *ServiceParameterInfo) DeepCopy() *ServiceParameterInfo {
	if in == nil {
		return nil
	}
	out := new(ServiceParameterInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in ServiceParameterList) DeepCopyInto(out *ServiceParameterList) {
	{
		in := &in
		*out = make(ServiceParameterList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceParameterList.
func (in ServiceParameterList) DeepCopy() ServiceParameterList {
	if in == nil {
		return nil
	}
	out := new(ServiceParameterList)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageBackend) DeepCopyInto(out *StorageBackend) {
	*out = *in
	if in.Services != nil {
		in, out := &in.Services, &out.Services
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ReplicationFactor != nil {
		in, out := &in.ReplicationFactor, &out.ReplicationFactor
		*out = new(int)
		**out = **in
	}
	if in.PartitionSize != nil {
		in, out := &in.PartitionSize, &out.PartitionSize
		*out = new(int)
		**out = **in
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageBackend.
func (in *StorageBackend) DeepCopy() *StorageBackend {
	if in == nil {
		return nil
	}
	out := new(StorageBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in StorageBackendList) DeepCopyInto(out *StorageBackendList) {
	{
		in := &in
		*out = make(StorageBackendList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageBackendList.
func (in StorageBackendList) DeepCopy() StorageBackendList {
	if in == nil {
		return nil
	}
	out := new(StorageBackendList)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *System) DeepCopyInto(out *System) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new System.
func (in *System) DeepCopy() *System {
	if in == nil {
		return nil
	}
	out := new(System)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *System) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemList) DeepCopyInto(out *SystemList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]System, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemList.
func (in *SystemList) DeepCopy() *SystemList {
	if in == nil {
		return nil
	}
	out := new(SystemList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SystemList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemSpec) DeepCopyInto(out *SystemSpec) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Location != nil {
		in, out := &in.Location, &out.Location
		*out = new(string)
		**out = **in
	}
	if in.Latitude != nil {
		in, out := &in.Latitude, &out.Latitude
		*out = new(string)
		**out = **in
	}
	if in.Longitude != nil {
		in, out := &in.Longitude, &out.Longitude
		*out = new(string)
		**out = **in
	}
	if in.Contact != nil {
		in, out := &in.Contact, &out.Contact
		*out = new(string)
		**out = **in
	}
	if in.DNSServers != nil {
		in, out := &in.DNSServers, &out.DNSServers
		*out = new(DNSServerList)
		if **in != nil {
			in, out := *in, *out
			*out = make(DNSServerList, len(*in))
			copy(*out, *in)
		}
	}
	if in.NTPServers != nil {
		in, out := &in.NTPServers, &out.NTPServers
		*out = new(NTPServerList)
		if **in != nil {
			in, out := *in, *out
			*out = make(NTPServerList, len(*in))
			copy(*out, *in)
		}
	}
	if in.PTP != nil {
		in, out := &in.PTP, &out.PTP
		*out = new(PTPInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.Certificates != nil {
		in, out := &in.Certificates, &out.Certificates
		*out = new(CertificateList)
		if **in != nil {
			in, out := *in, *out
			*out = make(CertificateList, len(*in))
			copy(*out, *in)
		}
	}
	if in.License != nil {
		in, out := &in.License, &out.License
		*out = new(LicenseInfo)
		**out = **in
	}
	if in.ServiceParameters != nil {
		in, out := &in.ServiceParameters, &out.ServiceParameters
		*out = new(ServiceParameterList)
		if **in != nil {
			in, out := *in, *out
			*out = make(ServiceParameterList, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(SystemStorageInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.VSwitchType != nil {
		in, out := &in.VSwitchType, &out.VSwitchType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemSpec.
func (in *SystemSpec) DeepCopy() *SystemSpec {
	if in == nil {
		return nil
	}
	out := new(SystemSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemStatus) DeepCopyInto(out *SystemStatus) {
	*out = *in
	if in.Defaults != nil {
		in, out := &in.Defaults, &out.Defaults
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemStatus.
func (in *SystemStatus) DeepCopy() *SystemStatus {
	if in == nil {
		return nil
	}
	out := new(SystemStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemStorageInfo) DeepCopyInto(out *SystemStorageInfo) {
	*out = *in
	if in.Backends != nil {
		in, out := &in.Backends, &out.Backends
		*out = new(StorageBackendList)
		if **in != nil {
			in, out := *in, *out
			*out = make(StorageBackendList, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
	if in.DRBD != nil {
		in, out := &in.DRBD, &out.DRBD
		*out = new(DRBDConfiguration)
		**out = **in
	}
	if in.FileSystems != nil {
		in, out := &in.FileSystems, &out.FileSystems
		*out = new(ControllerFileSystemList)
		if **in != nil {
			in, out := *in, *out
			*out = make(ControllerFileSystemList, len(*in))
			copy(*out, *in)
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemStorageInfo.
func (in *SystemStorageInfo) DeepCopy() *SystemStorageInfo {
	if in == nil {
		return nil
	}
	out := new(SystemStorageInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VFInfo) DeepCopyInto(out *VFInfo) {
	*out = *in
	in.CommonInterfaceInfo.DeepCopyInto(&out.CommonInterfaceInfo)
	if in.VFDriver != nil {
		in, out := &in.VFDriver, &out.VFDriver
		*out = new(string)
		**out = **in
	}
	if in.MaxTxRate != nil {
		in, out := &in.MaxTxRate, &out.MaxTxRate
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VFInfo.
func (in *VFInfo) DeepCopy() *VFInfo {
	if in == nil {
		return nil
	}
	out := new(VFInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in VFList) DeepCopyInto(out *VFList) {
	{
		in := &in
		*out = make(VFList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VFList.
func (in VFList) DeepCopy() VFList {
	if in == nil {
		return nil
	}
	out := new(VFList)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VLANInfo) DeepCopyInto(out *VLANInfo) {
	*out = *in
	in.CommonInterfaceInfo.DeepCopyInto(&out.CommonInterfaceInfo)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VLANInfo.
func (in *VLANInfo) DeepCopy() *VLANInfo {
	if in == nil {
		return nil
	}
	out := new(VLANInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in VLANList) DeepCopyInto(out *VLANList) {
	{
		in := &in
		*out = make(VLANList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VLANList.
func (in VLANList) DeepCopy() VLANList {
	if in == nil {
		return nil
	}
	out := new(VLANList)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeGroupInfo) DeepCopyInto(out *VolumeGroupInfo) {
	*out = *in
	if in.LVMType != nil {
		in, out := &in.LVMType, &out.LVMType
		*out = new(string)
		**out = **in
	}
	if in.PhysicalVolumes != nil {
		in, out := &in.PhysicalVolumes, &out.PhysicalVolumes
		*out = make(PhysicalVolumeList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeGroupInfo.
func (in *VolumeGroupInfo) DeepCopy() *VolumeGroupInfo {
	if in == nil {
		return nil
	}
	out := new(VolumeGroupInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in VolumeGroupList) DeepCopyInto(out *VolumeGroupList) {
	{
		in := &in
		*out = make(VolumeGroupList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeGroupList.
func (in VolumeGroupList) DeepCopy() VolumeGroupList {
	if in == nil {
		return nil
	}
	out := new(VolumeGroupList)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VxLANInfo) DeepCopyInto(out *VxLANInfo) {
	*out = *in
	if in.MulticastGroup != nil {
		in, out := &in.MulticastGroup, &out.MulticastGroup
		*out = new(string)
		**out = **in
	}
	if in.UDPPortNumber != nil {
		in, out := &in.UDPPortNumber, &out.UDPPortNumber
		*out = new(int)
		**out = **in
	}
	if in.TTL != nil {
		in, out := &in.TTL, &out.TTL
		*out = new(int)
		**out = **in
	}
	if in.EndpointMode != nil {
		in, out := &in.EndpointMode, &out.EndpointMode
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VxLANInfo.
func (in *VxLANInfo) DeepCopy() *VxLANInfo {
	if in == nil {
		return nil
	}
	out := new(VxLANInfo)
	in.DeepCopyInto(out)
	return out
}
