# permissions for end users to edit datanetworks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: datanetwork-editor-role
rules:
- apiGroups:
  - starlingx.windriver.com
  resources:
  - datanetworks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - starlingx.windriver.com
  resources:
  - datanetworks/status
  verbs:
  - get
