# permissions for end users to view datanetworks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: datanetwork-viewer-role
rules:
- apiGroups:
  - starlingx.windriver.com
  resources:
  - datanetworks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - starlingx.windriver.com
  resources:
  - datanetworks/status
  verbs:
  - get
