# permissions for end users to view hostprofiles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hostprofile-viewer-role
rules:
- apiGroups:
  - starlingx.windriver.com
  resources:
  - hostprofiles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - starlingx.windriver.com
  resources:
  - hostprofiles/status
  verbs:
  - get
