# permissions for end users to edit hosts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: host-editor-role
rules:
- apiGroups:
  - starlingx.windriver.com
  resources:
  - hosts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - starlingx.windriver.com
  resources:
  - hosts/status
  verbs:
  - get
