# permissions for end users to view platformnetworks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: platformnetwork-viewer-role
rules:
- apiGroups:
  - starlingx.windriver.com
  resources:
  - platformnetworks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - starlingx.windriver.com
  resources:
  - platformnetworks/status
  verbs:
  - get
