# permissions for end users to edit ptpinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ptpinstance-editor-role
rules:
- apiGroups:
  - starlingx.windriver.com
  resources:
  - ptpinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - starlingx.windriver.com
  resources:
  - ptpinstances/status
  verbs:
  - get
