# permissions for end users to view ptpinterfaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ptpinterface-viewer-role
rules:
- apiGroups:
  - starlingx.windriver.com
  resources:
  - ptpinterfaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - starlingx.windriver.com
  resources:
  - ptpinterfaces/status
  verbs:
  - get
