# permissions for end users to edit ptpinterfaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ptpinterface-editor-role
rules:
- apiGroups:
  - starlingx.windriver.com
  resources:
  - ptpinterfaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - starlingx.windriver.com
  resources:
  - ptpinterfaces/status
  verbs:
  - get
