kind: System
apiVersion: starlingx.windriver.com/v1beta1
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: vbox
  namespace: deployment
spec:
  description: Virtual Box Standard System (HTTPS)
  certificates:
    - type: ssl
      secret: platform-certificate
