
apiVersion: starlingx.windriver.com/v1
kind: PlatformNetwork
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: group0-data0v4
  namespace: deployment
spec:
  associatedAddressPools:
  - group0-data0v4-pool
  dynamic: true
  type: other
---
apiVersion: starlingx.windriver.com/v1
kind: AddressPool
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: group0-data0v4-pool
  namespace: deployment
spec:
  allocation:
    order: random
    ranges:
    - end: 192.168.57.10
      start: 192.168.57.2
  gateway: 192.168.57.1
  prefix: 24
  subnet: 192.168.57.0
---
apiVersion: starlingx.windriver.com/v1
kind: PlatformNetwork
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: group0-data1v4
  namespace: deployment
spec:
  associatedAddressPools:
  - group0-data1v4-pool
  dynamic: true
  type: other
---
apiVersion: starlingx.windriver.com/v1
kind: AddressPool
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: group0-data1v4-pool
  namespace: deployment
spec:
  allocation:
    order: sequential
    ranges:
    - end: 192.168.58.10
      start: 192.168.58.2
  gateway: 192.168.58.1
  prefix: 24
  subnet: 192.168.58.0
---
apiVersion: starlingx.windriver.com/v1
kind: PlatformNetwork
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: group0-data0v6
  namespace: deployment
spec:
  associatedAddressPools:
  - group0-data0v6-pool
  dynamic: true
  type: other
---
apiVersion: starlingx.windriver.com/v1
kind: AddressPool
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: group0-data0v6-pool
  namespace: deployment
spec:
  allocation:
    order: sequential
    ranges:
    - end: fd00:0:0:1::a
      start: fd00:0:0:1::2
  gateway: fd00:0:0:1::1
  prefix: 64
  subnet: 'fd00:0:0:1::'
---
apiVersion: starlingx.windriver.com/v1
kind: PlatformNetwork
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: group0-data1v6
  namespace: deployment
spec:
  associatedAddressPools:
  - group0-data1v6-pool
  dynamic: true
  type: other
---
apiVersion: starlingx.windriver.com/v1
kind: AddressPool
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: group0-data1v6-pool
  namespace: deployment
spec:
  allocation:
    order: sequential
    ranges:
    - end: fd00:0:0:2::a
      start: fd00:0:0:2::2
  gateway: fd00:0:0:2::1
  prefix: 64
  subnet: 'fd00:0:0:2::'
---
apiVersion: starlingx.windriver.com/v1
kind: PlatformNetwork
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: oam
  namespace: deployment
spec:
  associatedAddressPools:
  - oam-ipv4
  - oam-ipv6
  dynamic: false
  type: oam
status:
  deploymentScope: principal
---
apiVersion: starlingx.windriver.com/v1
kind: AddressPool
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: oam-ipv4
  namespace: deployment
spec:
  allocation:
    order: random
    ranges:
    - end: 10.10.10.254
      start: 10.10.10.2
  floatingAddress: 10.10.10.2
  controller0Address: 10.10.10.3
  controller1Address: 10.10.10.4
  prefix: 24
  subnet: 10.10.10.1
---
apiVersion: starlingx.windriver.com/v1
kind: AddressPool
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: oam-ipv6
  namespace: deployment
spec:
  allocation:
    order: random
    ranges:
    - end: fcff:10::a
      start: fcff:10::2
  floatingAddress: fcff:10::2
  controller0Address: fcff:10::3
  controller1Address: fcff:10::4
  prefix: 64
  subnet: fcff:10::1
