apiVersion: v1
kind: Namespace
metadata:
  name: deployment
---
apiVersion: v1
data:
  ca.crt: ""
  tls.crt: ""
  tls.key: ""
kind: Secret
metadata:
  name: platform-certificate
  namespace: deployment
type: kubernetes.io/tls
---
apiVersion: v1
data:
  OS_PASSWORD: U3Q4cmxpbmdYKg==
  OS_USERNAME: YWRtaW4=
kind: Secret
metadata:
  name: system-endpoint
  namespace: deployment
stringData:
  OS_AUTH_TYPE: password
  OS_AUTH_URL: http://192.168.204.1:5000/v3
  OS_ENDPOINT_TYPE: internalURL
  OS_IDENTITY_API_VERSION: "3"
  OS_INTERFACE: internal
  OS_KEYSTONE_REGION_NAME: RegionOne
  OS_PROJECT_DOMAIN_NAME: Default
  OS_PROJECT_NAME: admin
  OS_REGION_NAME: RegionOne
type: Opaque
---
apiVersion: starlingx.windriver.com/v1
kind: DataNetwork
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: group0-data0b
  namespace: deployment
spec:
  description: group0 data networks for the shared internal networks.
  mtu: 1500
  type: vlan
---
apiVersion: starlingx.windriver.com/v1
kind: DataNetwork
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: group0-data0
  namespace: deployment
spec:
  description: group0 data networks for the tenant1 networks.
  mtu: 1500
  type: vlan
---
apiVersion: starlingx.windriver.com/v1
kind: DataNetwork
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: group0-data1
  namespace: deployment
spec:
  description: group0 data networks for the tenant2 networks.
  mtu: 1500
  type: vlan
---
apiVersion: starlingx.windriver.com/v1
kind: DataNetwork
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: group0-ext0
  namespace: deployment
spec:
  description: group0 data networks for the external networks.
  mtu: 1500
  type: vlan
---
apiVersion: starlingx.windriver.com/v1
kind: Host
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: controller-0
  namespace: deployment
spec:
  match:
    bootMAC: CONTROLLER0MAC
  overrides:
    location: vbox
  profile: controller-profile
---
apiVersion: starlingx.windriver.com/v1
kind: HostProfile
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: controller-profile
  namespace: deployment
spec:
  administrativeState: unlocked
  bootDevice: /dev/disk/by-path/pci-0000:00:0d.0-ata-1.0
  console: tty0
  installOutput: text
  interfaces:
    ethernet:
    - class: platform
      name: lo
      platformNetworks:
      - mgmt
      - cluster-host
      port:
        name: lo
    - class: platform
      name: oam0
      platformNetworks:
      - oam
      port:
        name: enp0s3
    - class: data
      dataNetworks:
      - group0-data0
      - group0-data0b
      - group0-ext0
      name: data0
      port:
        name: eth1000
    - class: data
      dataNetworks:
      - group0-data1
      name: data1
      port:
        name: eth1001
  labels:
    openstack-compute-node: enabled
    openstack-control-plane: enabled
    openvswitch: enabled
    sriov: enabled
  personality: controller
  processors:
  - functions:
    - count: 0
      function: vswitch
    node: 0
  provisioningMode: dynamic
  rootDevice: /dev/disk/by-path/pci-0000:00:0d.0-ata-1.0
  storage:
    osds:
    - function: osd
      path: /dev/disk/by-path/pci-0000:00:0d.0-ata-2.0
    volumeGroups:
    - name: nova-local
      physicalVolumes:
      - path: /dev/disk/by-path/pci-0000:00:0d.0-ata-1.0
        size: 4
        type: partition
  subfunctions:
  - controller
  - worker
---
apiVersion: starlingx.windriver.com/v1
kind: System
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: vbox
  namespace: deployment
spec:
  certificates:
  - secret: platform-certificate
    type: ssl
  contact: info@windriver.com
  description: Virtual Box Standard System (HTTPS)
  location: vbox
  ntpServers:
  - 0.pool.ntp.org
  - 1.pool.ntp.org
  - 2.pool.ntp.org
  storage:
    backends:
    - name: ceph-store
      type: ceph
