apiVersion: v1
kind: Namespace
metadata:
  name: deployment
---
apiVersion: v1
data:
  OS_PASSWORD: U3Q4cmxpbmdYKg==
  OS_USERNAME: YWRtaW4=
kind: Secret
metadata:
  name: system-endpoint
  namespace: deployment
stringData:
  OS_AUTH_TYPE: password
  OS_AUTH_URL: http://192.168.204.1:5000/v3
  OS_ENDPOINT_TYPE: internalURL
  OS_IDENTITY_API_VERSION: "3"
  OS_INTERFACE: internal
  OS_KEYSTONE_REGION_NAME: RegionOne
  OS_PROJECT_DOMAIN_NAME: Default
  OS_PROJECT_NAME: admin
  OS_REGION_NAME: RegionOne
type: Opaque
---
apiVersion: starlingx.windriver.com/v1
kind: DataNetwork
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: group0-data0b
  namespace: deployment
spec:
  description: group0 data networks for the shared internal networks.
  mtu: 1500
  type: vlan
---
apiVersion: starlingx.windriver.com/v1
kind: DataNetwork
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: group0-data0
  namespace: deployment
spec:
  description: group0 data networks for the tenant1 networks.
  mtu: 1500
  type: vlan
---
apiVersion: starlingx.windriver.com/v1
kind: DataNetwork
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: group0-data1
  namespace: deployment
spec:
  description: group0 data networks for the tenant2 networks.
  mtu: 1500
  type: vlan
---
apiVersion: starlingx.windriver.com/v1
kind: DataNetwork
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: group0-ext0
  namespace: deployment
spec:
  description: group0 data networks for the external networks.
  mtu: 1500
  type: vlan
---
apiVersion: starlingx.windriver.com/v1
kind: DataNetwork
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: group0-vxlan-ext0
  namespace: deployment
spec:
  description: group0 data networks for the external networks.
  mtu: 1400
  type: vxlan
  vxlan:
    endpointMode: dynamic
    multicastGroup: 239.0.2.1
    ttl: 10
    udpPortNumber: 8472
---
apiVersion: starlingx.windriver.com/v1
kind: DataNetwork
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: group0-vxlan0b
  namespace: deployment
spec:
  description: group0 vxlan data networks for the shared internal networks.
  mtu: 1400
  type: vxlan
  vxlan:
    endpointMode: dynamic
    multicastGroup: 239.0.1.10
    ttl: 10
    udpPortNumber: 4789
---
apiVersion: starlingx.windriver.com/v1
kind: DataNetwork
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: group0-vxlan0
  namespace: deployment
spec:
  description: group0 vxlan data networks for the tenant1 networks.
  mtu: 1400
  type: vxlan
  vxlan:
    endpointMode: static
    ttl: 10
    udpPortNumber: 4789
---
apiVersion: starlingx.windriver.com/v1
kind: DataNetwork
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: group0-vxlan1
  namespace: deployment
spec:
  description: group0 vxlan data networks for the tenant2 networks.
  mtu: 1400
  type: vxlan
  vxlan:
    endpointMode: static
    ttl: 10
    udpPortNumber: 4789
---
apiVersion: starlingx.windriver.com/v1
kind: Host
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: controller-0
  namespace: deployment
spec:
  match:
    bootMAC: CONTROLLER0MAC
  overrides:
    addresses:
    - address: 192.168.59.2
      interface: vlan11
      prefix: 24
    - address: fd00:0:0:b::2
      interface: vlan11
      prefix: 64
    location: vbox
  profile: controller-profile
---
apiVersion: starlingx.windriver.com/v1
kind: HostProfile
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: controller-profile
  namespace: deployment
spec:
  administrativeState: unlocked
  bootDevice: /dev/disk/by-path/pci-0000:00:0d.0-ata-1.0
  console: tty0
  installOutput: text
  interfaces:
    ethernet:
    - class: platform
      name: lo
      platformNetworks:
      - mgmt
      - cluster-host
      port:
        name: lo
    - class: platform
      name: oam0
      platformNetworks:
      - oam
      port:
        name: enp0s3
    - class: data
      dataNetworks:
      - group0-vxlan0
      - group0-vxlan0b
      name: data0
      platformNetworks:
      - group0-data0v4
      - group0-data0v6
      port:
        name: eth1000
    - class: data
      dataNetworks:
      - group0-vxlan1
      name: data1
      platformNetworks:
      - group0-data1v4
      - group0-data1v6
      port:
        name: eth1001
    vlan:
    - class: data
      dataNetworks:
      - group0-vxlan-ext0
      lower: data0
      name: vlan11
      vid: 11
  labels:
    openstack-compute-node: enabled
    openstack-control-plane: enabled
    openvswitch: enabled
    sriov: enabled
  personality: controller
  processors:
  - functions:
    - count: 0
      function: vswitch
    node: 0
  provisioningMode: dynamic
  rootDevice: /dev/disk/by-path/pci-0000:00:0d.0-ata-1.0
  routes:
  - gateway: 192.168.57.1
    interface: data0
    prefix: 0
    subnet: 0.0.0.0
  - gateway: 192.168.58.1
    interface: data1
    prefix: 0
    subnet: 0.0.0.0
  - gateway: 192.168.59.1
    interface: vlan11
    prefix: 0
    subnet: 0.0.0.0
  - gateway: fd00:0:0:1::1
    interface: data0
    prefix: 0
    subnet: '::'
  - gateway: fd00:0:0:2::1
    interface: data1
    prefix: 0
    subnet: '::'
  - gateway: fd00:0:0:b::1
    interface: vlan11
    prefix: 0
    subnet: '::'
  storage:
    osds:
    - function: osd
      path: /dev/disk/by-path/pci-0000:00:0d.0-ata-2.0
    volumeGroups:
    - name: nova-local
      physicalVolumes:
      - path: /dev/disk/by-path/pci-0000:00:0d.0-ata-1.0
        size: 4
        type: partition
  subfunctions:
  - controller
  - worker
---
apiVersion: starlingx.windriver.com/v1
kind: PlatformNetwork
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: group0-data0v4
  namespace: deployment
spec:
  allocation:
    order: random
    ranges:
    - end: 192.168.57.10
      start: 192.168.57.2
    type: dynamic
  gateway: 192.168.57.1
  prefix: 24
  subnet: 192.168.57.0
  type: other
---
apiVersion: starlingx.windriver.com/v1
kind: PlatformNetwork
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: group0-data0v6
  namespace: deployment
spec:
  allocation:
    order: sequential
    ranges:
    - end: fd00:0:0:1::a
      start: fd00:0:0:1::2
    type: dynamic
  gateway: fd00:0:0:1::1
  prefix: 64
  subnet: 'fd00:0:0:1::'
  type: other
---
apiVersion: starlingx.windriver.com/v1
kind: PlatformNetwork
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: group0-data1v4
  namespace: deployment
spec:
  allocation:
    order: sequential
    ranges:
    - end: 192.168.58.10
      start: 192.168.58.2
    type: dynamic
  gateway: 192.168.58.1
  prefix: 24
  subnet: 192.168.58.0
  type: other
---
apiVersion: starlingx.windriver.com/v1
kind: PlatformNetwork
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: group0-data1v6
  namespace: deployment
spec:
  allocation:
    order: sequential
    ranges:
    - end: fd00:0:0:2::a
      start: fd00:0:0:2::2
    type: dynamic
  gateway: fd00:0:0:2::1
  prefix: 64
  subnet: 'fd00:0:0:2::'
  type: other
---
apiVersion: starlingx.windriver.com/v1
kind: System
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: vbox
  namespace: deployment
spec:
  contact: info@windriver.com
  description: Virtual Box Standard System
  location: vbox
  ntpServers:
  - 0.pool.ntp.org
  - 1.pool.ntp.org
  - 2.pool.ntp.org
  storage:
    backends:
    - name: ceph-store
      type: ceph
