# SPDX-License-Identifier: Apache-2.0
# Copyright(c) 2021-2022 Wind River Systems, Inc.

# Default values for Deployment Manager instances

replicaCount: 1

namespace: platform-deployment-manager

# Set the resource name override to be the short form since the helm chart
# name is overly long.
nameOverride: platform-deployment-manager

imagePullSecrets:
 - name: default-registry-key

rbacProxy:
  enabled: true
  port: 8443
  image: gcr.io/kubebuilder/kube-rbac-proxy:v0.11.0
  logLevel: 10

manager:
  debugger:
    enabled: false
    wait: false
    port: 30000
  logLevel: info     # one of 'debug', 'info', 'error', or any integer value > 0
  stacktrace: error  # one of 'info', 'error', 'panic
  image:
    repository: wind-river/cloud-platform-deployment-manager
    tag: latest
    pullPolicy: IfNotPresent
  configmap:
    reconcilers:
      system:
        certificate:
          httpsRequired: false
      host:
        bmc:
          httpsRequired: false

tolerations:
  - key: "node-role.kubernetes.io/master"
    operator: "Exists"
    effect: "NoSchedule"

resources: {}
# NOTE(alegacy): disabled until required.
#  limits:
#    cpu: 100m
#    memory: 30Mi
#  requests:
#    cpu: 100m
#    memory: 20Mi
