# SPDX-License-Identifier: Apache-2.0
# Copyright(c) 2019 Wind River Systems, Inc.

# Default values for Deployment Manager instances

replicaCount: 1

namespace: platform-deployment-manager

# Set the resource name override to be the short form since the helm chart
# name is overly long.
nameOverride: platform-deployment-manager

imagePullSecrets: []

rbacProxy:
  enabled: true
  port: 8443
  image: gcr.io/kubebuilder/kube-rbac-proxy:v0.4.0
  logLevel: 10

manager:
  debugger:
    enabled: false
    wait: false
    port: 30000
  logLevel: 0
  image:
    repository: wind-river/cloud-platform-deployment-manager
    tag: latest
    pullPolicy: IfNotPresent
  configmap:
    reconcilers:
      system:
        certificate:
          httpsRequired: false
      host:
        bmc:
          httpsRequired: false

resources: {}
# NOTE(alegacy): disabled until required.
#  limits:
#    cpu: 100m
#    memory: 30Mi
#  requests:
#    cpu: 100m
#    memory: 20Mi
