apiVersion: v1
data:
  ca.crt: ""
  tls.crt: ""
  tls.key: ""
kind: Secret
metadata:
  name: system-local-ca
  namespace: cert-manager
type: kubernetes.io/tls
---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: system-local-ca
spec:
  ca:
    secretName: system-local-ca
---
# StarlingX REST & GUI Certificate
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: system-restapi-gui-certificate
  namespace: deployment
spec:
  secretName: system-restapi-gui-certificate
  issuerRef:
    name: system-local-ca
    kind: ClusterIssuer
  duration: 2160h    # 90d
  renewBefore: 360h  # 15d
  commonName: null # Common Name
  subject:
    countries:
    - null # Country
    provinces:
    - null # State/Province
    organizationalUnits:
    - WRCP-System
  ipAddresses:
  -  null # OAM floating IP
  dnsNames:
  - null # OAM IP or FQDN 
---
# StarlingX Docker Registry Certificate
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: system-registry-local-certificate
  namespace: deployment
spec:
  secretName: system-registry-local-certificate
  issuerRef:
    name: system-local-ca
    kind: ClusterIssuer
  duration: 2160h    # 90d
  renewBefore: 360h  # 15d
  subject:
    countries:
    - null # Country
    provinces:
    - null # State/Province
    organizationalUnits:
    - WRCP-System
  ipAddresses:
  - null # oam floating IP address
  - null # oam mgmt IP address
  dnsNames:
  - registry.local
  - registry.central
---