kind: System
apiVersion: starlingx.windriver.com/v1
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: vbox
  namespace: deployment
spec:
  description: Virtual Box Standard System (HTTPS)
  certificates:
  - secret: system-restapi-gui-certificate
    type: ssl
  - secret: system-registry-local-certificate
    type: docker_registry