name: Go test CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  go-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.23.5'

    - name: Test the commit
      run: make test

    - name: Build deployctl
      run: make tools

  golangci-lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        # when the files to be extracted are already present,
        # tar extraction in Golangci Lint fails with the "File exists"
        # errors. These files appear to be present because of
        # cache in setup-go, on disabling the cache we are no more seeing
        # such error. Cache is to be enabled once the fix is available for
        # this issue
        go-version: '1.23.5'
        cache: false

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v4
      with:
        version: v1.64.8
        args: "-v --timeout 15m0s"
